


// import React, { useEffect, useState, useRef } from "react";
// import { useParams } from "react-router-dom";
// import { useGrocery } from "@/contexts/GroceryContext";
// import { formatCurrency } from "@/utils/currency";
// import { useLanguage } from "@/contexts/LanguageContext";
// import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableFooter } from "@/components/ui/table";
// import { Button } from "@/components/ui/button";
// import html2pdf from "html2pdf.js";

// const PrintPreview = () => {
//   const { id } = useParams<{ id: string }>();
//   const { getListById } = useGrocery();
//   const { language } = useLanguage();
//   const [list, setList] = useState<any>(null);
//   const printRef = useRef<HTMLDivElement>(null);

//   useEffect(() => {
//     if (id) {
//       const groceryList = getListById(id);
//       if (groceryList) {
//         setList(groceryList);
//       }
//     }
//   }, [id, getListById]);

//   const handleDownloadPDF = () => {
//     if (!printRef.current) return;

//     const opt = {
//       margin: 0.5,
//       filename: `${list?.title || "grocery-list"}.pdf`,
//       image: { type: 'jpeg', quality: 0.98 },
//       html2canvas: { scale: 2, useCORS: true }, // Added useCORS to handle fonts
//       jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
//     };

//     html2pdf().set(opt).from(printRef.current).save();
//   };

//   if (!list) {
//     return <div className="p-8 text-center">List not found</div>;
//   }

//   return (
//     <div className="p-8 max-w-4xl mx-auto">
//       <style>
//         {`
//           @media print {
//             body {
//               print-color-adjust: exact;
//               -webkit-print-color-adjust: exact;
//               font-family: 'Noto Sans Bengali', Arial, sans-serif !important;
//             }
//             @page {
//               size: A4;
//               margin: 1cm;
//             }
//             .print-table th, 
//             .print-table td {
//               padding: 8px;
//               text-align: left;
//               border: 1px solid #ddd;
//               font-family: 'Noto Sans Bengali', Arial, sans-serif !important;
//             }
//             .print-table th {
//               background-color: #ff8c00 !important;
//               color: white !important;
//             }
//             .print-table tr {
//               background-color: transparent !important; /* Remove hover effect in print */
//             }
//             .price-column {
//               text-align: right !important;
//             }
//             * {
//               font-family: 'Noto Sans Bengali', Arial, sans-serif !important;
//             }
//           }
//           .print-table tr:hover {
//             background-color: #f9f9f9; /* Consistent hover effect for screen */
//           }
//         `}
//       </style>

//       <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500;700&display=swap" />

//       <div className="flex justify-end mb-4">
//         <Button onClick={handleDownloadPDF} className="bg-orange-600 hover:bg-orange-500 text-white">
//           Download PDF
//         </Button>
//       </div>

//       <div ref={printRef}>
//         <div className="mb-8">
//           <h1 className="text-3xl font-bold mb-2">{list.title}</h1>
//           <p className="text-gray-600">
//             {list.month} {list.year} • Created on {new Date(list.createdAt).toLocaleDateString()}
//           </p>
//           <p className="text-sm text-gray-500 mt-2">Generated by BazarBuddy</p>
//         </div>

//         <Table className="w-full print-table" style={{ fontFamily: "'Noto Sans Bengali', Arial, sans-serif" }}>
//           <TableHeader>
//             <TableRow className="bg-orange-600 text-white">
//               <TableHead className="border border-gray-300 text-white text-center">Item</TableHead>
//               <TableHead className="border border-gray-300 text-white text-center">Quantity</TableHead>
//               <TableHead className="border border-gray-300 text-white text-center">Unit</TableHead>
//               <TableHead className="border border-gray-300 text-white text-right price-column">Est. Price (৳)</TableHead>
//             </TableRow>
//           </TableHeader>
//           <TableBody>
//             {list.items.map((item: any) => (
//               <TableRow key={item.id} className="print-table-row">
//                 <TableCell className="border hover:bg- border-gray-300">{item.name}</TableCell>
//                 <TableCell className="border hover:bg- border-gray-300">{item.quantity}</TableCell>
//                 <TableCell className="border hover:bg- border-gray-300">{item.unit}</TableCell>
//                 <TableCell className="border hover:bg- border-gray-300 text-right price-column">
//                   {item.estimatedPrice ? formatCurrency(item.estimatedPrice, 'BDT') : '৳0.00'}
//                 </TableCell>
//               </TableRow>
//             ))}
//           </TableBody>
//           <TableFooter>
//             <TableRow className="bg-gray-100 font-bold">
//               <TableCell className="border border-gray-300" colSpan={3} align="right">Total:</TableCell>
//               <TableCell className="border border-gray-300 text-right price-column">
//                 {formatCurrency(list.totalEstimatedPrice, 'BDT')}
//               </TableCell>
//             </TableRow>
//           </TableFooter>
//         </Table>

//         <div className="mt-8 text-center text-gray-500 text-sm">
//           <p>Printed on {new Date().toLocaleDateString()}</p>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default PrintPreview;

import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import { useGrocery } from "@/contexts/GroceryContext";
import { formatCurrency } from "@/utils/currency";
import { getText } from "@/utils/translations";
import { useLanguage } from "@/contexts/LanguageContext";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableFooter } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import html2pdf from "html2pdf.js";
import { toBengaliNumerals } from "@/utils/numbers";
import { format } from "date-fns";
import { bn as bnLocale } from "date-fns/locale";

const PrintPreview = () => {
  const { id } = useParams<{ id: string }>();
  const { getListById } = useGrocery();
  const { language, isEnglish } = useLanguage();
  const [list, setList] = useState<any>(null);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (id) {
      const groceryList = getListById(id);
      if (groceryList) {
        setList(groceryList);
      }
    }
  }, [id, getListById]);

  const handleDownloadPDF = () => {
    if (!printRef.current) return;

    const opt = {
      margin: 0.5,
      filename: `${list?.title || "grocery-list"}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(printRef.current).save();
  };

  if (!list) {
    return <div className="p-8 text-center text-gray-500">List not found</div>;
  }

  return (
    <div className="p-6 max-w-5xl mx-auto bg-gray-50">
      <style>
        {`
          @media print {
            body {
              font-family: 'Noto Sans Bengali', Arial, sans-serif;
              print-color-adjust: exact;
              -webkit-print-color-adjust: exact;
            }
            @page {
              size: A4;
              margin: 1cm;
            }
            .print-table th, .print-table td {
              border: 1px solid #ccc;
              padding: 10px;
              text-align: left;
            }
            .print-table th {
              background-color: #F97316 !important;
              color: white !important;
            }
            .price-column {
              text-align: right !important;
            }
          }
        `}
      </style>

      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500;700&display=swap"
      />

      <div className="flex justify-between items-center mb-6 print:hidden">
        <h2 className="text-xl font-semibold">{getText("printPreview", language)}</h2>
        <Button onClick={handleDownloadPDF} className="bg-orange-600 hover:bg-orange-500 text-white">
          {getText("print", language)}
        </Button>
      </div>

      <div ref={printRef} className="bg-white p-8 shadow-md rounded-xl">
        <header className="mb-6 border-b pb-4">
          <h1 className="text-3xl font-bold text-gray-800 mb-1">{list.title}</h1>
          <p className="text-gray-600">
            {isEnglish ? list.month : getText(list.month.toLowerCase(), language)} {isEnglish ? list.year : toBengaliNumerals(list.year)} • {getText("createdOn", language)} {list.createdAt ? format(new Date(list.createdAt), isEnglish ? "MM/dd/yyyy" : "dd/MM/yyyy", { locale: !isEnglish ? bnLocale : undefined }) : "N/A"}
          </p>
          <p className="text-sm text-gray-500 mt-1">{getText("generatedBy", language)} BazarBuddy</p>
        </header>

        <Table className="w-full print-table text-sm" style={{ fontFamily: "'Noto Sans Bengali', Arial, sans-serif" }}>
          <TableHeader>
            <TableRow className="bg-orange-600 text-white text-sm">
              <TableHead className="text-white text-left">{getText("item", language)}</TableHead>
              <TableHead className="text-white text-left">{getText("quantity", language)}</TableHead>
              <TableHead className="text-white text-left">{getText("unit", language)}</TableHead>
              <TableHead className="text-white text-right price-column">{getText("estPriceBdt", language)}</TableHead>
            </TableRow>
          </TableHeader>

          <TableBody>
            {list.items.map((item: any) => (
              <TableRow key={item.id}>
                <TableCell className="border text-gray-950 border-gray-200 hover:bg-gray-400">{item.name}</TableCell>
                <TableCell className="border text-gray-950 border-gray-200 hover:bg-gray-400">{isEnglish ? item.quantity : toBengaliNumerals(item.quantity)}</TableCell>
                <TableCell className="border text-gray-950 border-gray-200 hover:bg-gray-400">{isEnglish ? item.unit : getText(item.unit, language)}</TableCell>
                <TableCell className="border text-gray-950 border-gray-200 hover:bg-gray-400 text-right price-column">
                  {item.estimatedPrice ? formatCurrency(item.estimatedPrice, 'BDT', !isEnglish) : (isEnglish ? '$0.00' : '৳০.০০')}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>

          <TableFooter>
            <TableRow className="bg-gray-100 font-semibold">
              <TableCell colSpan={3} className=" text-gray-950 hover:bg-gray-400 text-right border border-gray-200">{getText("total", language)}:</TableCell>
              <TableCell className=" text-gray-950 text-right border hover:bg-gray-400 border-gray-200 price-column">
                {formatCurrency(list.totalEstimatedPrice, 'BDT', !isEnglish)}
              </TableCell>
            </TableRow>
          </TableFooter>
        </Table>

        <footer className="mt-6 text-center text-gray-500 text-xs">
          <p>{getText("printedOn", language)} {format(new Date(), isEnglish ? "MM/dd/yyyy" : "dd/MM/yyyy", { locale: !isEnglish ? bnLocale : undefined })}</p>
        </footer>
      </div>
    </div>
  );
};

export default PrintPreview;
